name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SSH_KEY: $
      SSH_HOSTNAME: $
      SSH_PORT: $
      SSH_USER: $

    steps:
      - run: mkdir ~/.ssh
      - run: 'echo "$SSH_KEY" >> ~/.ssh/github-action'
      - run: chmod 400 ~/.ssh/github-action
      - run: echo -e 'Host vortezzdev\n\tUser "$SSH_USER"\n\tHostname "$SSH_HOSTNAME"\n\tPort "$SSH_PORT"\n\tIdentityFile ~/.ssh/github-action' >> ~/.ssh/config
      - run: ssh vortezz "sh build.sh"